apiVersion: apps/v1
kind: Deployment
metadata:
  name: front6
  labels:
    app: front6
spec:
  replicas: 1
  selector:
    matchLabels:
      app: front6
  template:
    metadata:
      labels:
        app: front6
    spec:
      containers:
      - name: frontend
        image: registry.home-k8s.lab/k8s/nouurrr/app # image Docker du frontend
        ports:
        - containerPort: 80
